apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: ingress
  rules:
  - http:
      paths:
      - backend:
          service:
            name: web-service-develop
            port:
              number: 3000
        path: /
        pathType: Exact
