apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: web-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30007
  selector:
    run: web-develop
